version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    volumes:
      - mysql_data:/var/lib/mysqlfolder
    environment:
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'mypassword'
      MYSQL_DATABASE: 'sokol_db'
    ports:
      - '3306:3306'

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  web:
    build: .
    restart: always
    volumes:
      - ./sokol/:/app
    ports:
     - "5000:5000"
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  mysql_data:
  static_value:
  media_value:
