# Generated by Django 5.0.2 on 2024-03-02 23:34

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_email',
            field=models.EmailField(max_length=254, verbose_name='Почта заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Тлефон заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_address',
            field=models.TextField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_delivery_method',
            field=models.TextField(verbose_name='Выбранный способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_price',
            field=models.FloatField(verbose_name='Стоимость заказа в рублях'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_products',
            field=models.ManyToManyField(related_name='orders', to='products.product', verbose_name='Список заказанных товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_status',
            field=models.TextField(verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(related_name='products', to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Цена в рублях'),
        ),
    ]
