# Generated by Django 5.0.2 on 2024-03-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_order_customer_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_address',
            new_name='order_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordered_delivery_method',
            new_name='order_delivery_method',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordered_price',
            new_name='order_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('awaiting_payment', 'Ожидает оплаты'), ('in_assembly', 'В сборке'), ('transferred_to_delivery', 'Передаётся в доставку'), ('on_the_way', 'В пути'), ('awaiting_receipt', 'Ожидает получения'), ('received', 'Получен '), ('canceled', 'Отменен')], default='awaiting_payment', max_length=40, verbose_name='Статус заказа'),
        ),
    ]
