# Generated by Django 5.0.2 on 2024-03-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_ordered_address_order_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.TextField(default=0, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='/product_img/default_product_detail_img.jpg.jpg', upload_to='product_img/', verbose_name='Картинка 536x639 для страницы продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, upload_to='product_img/', verbose_name='Картинка 1140x760 для описания на странице продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='laser_sight',
            field=models.BooleanField(blank=True, null=True, verbose_name='С ЛЦУ'),
        ),
    ]
