# Generated by Django 5.0.2 on 2024-03-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/сategory_img/default_сategory_img.png', upload_to='сategory_img/', verbose_name='Картинка 896x485 для показа в списках'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='/product_img/default_product_detail_img.png', upload_to='product_img/', verbose_name='Картинка 536x639 для страницы продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=models.ImageField(default='/product_img/default_products_list_img.png', upload_to='product_img/', verbose_name='Картинка 433x516 для показа в списках'),
        ),
    ]
