# Generated by Django 5.0.2 on 2024-03-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_patronymic_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram заказчика'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='VK заказчика'),
        ),
    ]
