# Generated by Django 5.0.2 on 2024-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_telegram_customuser_vk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='VK'),
        ),
    ]
